//-----------------------------------------------------------------------------
// Copyright (C) Proxmark3 contributors. See AUTHORS.md for details.
//
// This code is licensed to you under the terms of the GNU GPL, version 3 or,
// at your option, any later version. See the LICENSE.txt file for the text of
// the license.
//-----------------------------------------------------------------------------
// Version information on fpga images
//
// This file is generated by fpga_compress. Don't edit!
//-----------------------------------------------------------------------------


#include "fpga.h"

const int g_fpga_bitstream_num = 4;
const FPGA_VERSION_INFORMATION g_fpga_version_information[4] = {
    { "fpga_pm3_hf.ncd image 2s30vq100 2024-02-03 15:12:20", FPGA_BITSTREAM_HF },
    { "fpga_pm3_lf.ncd image 2s30vq100 2024-02-03 15:12:10", FPGA_BITSTREAM_LF },
    { "fpga_pm3_felica.ncd image 2s30vq100 2024-02-03 15:12:41", FPGA_BITSTREAM_HF_FELICA },
    { "fpga_pm3_hf_15.ncd image 2s30vq100 2024-02-03 15:12:31", FPGA_BITSTREAM_HF_15 }
};
